name: PR
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    strategy:
      matrix:
        python-version: [3.9]
        step: ['test']
        # step: ['lint', 'test:chain']
    name: test chaintester
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install pytest
          python3 -m pip install gscdk
      - name: Install EOS test framework
        run: |
          python3 -m pip install ipyeos
      - name: Run eos-debugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eos-debugger &
      - name: test
        run: |
          pushd test
          ./build.sh
          popd
          go test
